### ISSUE TITLE
你好，你这个是ios和android都支持吗？

### ISSUE THREAD

**Issue by kiyeer** [pinzi/GeTui-PushApi-NetCoreSDK-V2#1]
我测试了ios，根据cid单推，收不到消息，同样的cid，用uniapp 官方后端推送可以接收到。

**Comment by pinzi** [comment]
这个是对官方api的封装，是支持ios和Android的。你是用哪种方式调用的呢？

**Comment by kiyeer** [comment]
使用下面的方法：
IStorage iStorage = new RedisStorage(new StackExchangeRedis(new RedisOptions()
{
    Host = "127.0.0.1",
    Port = 6379,
    DbNum = 10
}));
var options = new GeTuiPushOptions()
{
    AppID = AppID,
    AppKey = AppKey,
    MasterSecret = MasterSecret
};
GeTuiPushV2Api api = new GeTuiPushV2Api();
GeTuiPushService service = new GeTuiPushService(iStorage, options, api);
try
{
    await service.PushMessageAsync(new PushMessageInDto()
    {
        title = "停机警告",
        body = "已停机，请及时处理",
        payload = JsonConvert.SerializeObject(new
        {
            msgId = new string[] { Guid.NewGuid().ToStr() },
            text = $"停机时间：{DateTime.Now}"
        }),
        isall = false,
        uid = new string[] { "123456789" }
    });
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}

**Comment by kiyeer** [comment]
你这个调用不用特别区分ios和android，直接传参数即可，是吗？

**Comment by pinzi** [comment]
> 你用这个不需要额外的参数吗？

没有额外参数的，这些代码我已经在公司的项目中验证过的，你是安装了nuget包吗？那个打包可能存在问题，因为我请假了，所以就没有来得及去验证nuget包。
你需要注意的是，参数里面的uid是自己系统中的用户唯一标识，这个是用来和cid进行关联的。我们把cid和uid的关联存在redis中，推送的时候传入uid就能获取到对应的cid。
你先用我这个完整的源码项目GeTuiPushApiV2.ServerSDK.Core.Test进行测试，先在uni-app中获取到一个cid，再用自定义的uid做key来保存这个cid到redis中，然后测试一下能否推送。
特别提醒，源码中的appkey，id之类的都是我的账号申请的，你需要换自己的账号去申请并替换掉。

**Comment by kiyeer** [comment]
- 嗯，我都替换了，缓存地址这些也设置了，测试的时候看了缓存中有uid及对应的cid的值。appid,appkey这些用了uniapp后端对应的值，不过我是下载你的源码重新编译然后引用的。测试的时候没有错误捕捉到。我再用安卓的试试看。

**Comment by pinzi** [comment]
nuget包是有问题的，我刚才改了半天都没搞定，暂时下架了，你可以先用源码项目测试，你拉一下。我做了测试，可以推送成功的。要注意的是，需要用自定义基座来测试或者打包成正式包才能测试，直接用普通基座是无法推送的。注意manifest.json中配置的appid和schemes包名是否和后台一致。

**Comment by pinzi** [comment]
````
//3.使用自定义的接口封装方法
            {
                IStorage iStorage = new RedisStorage(new StackExchangeRedis(new RedisOptions()
                {
                    Host = "127.0.0.1",
                    Port = 6379,
                    DbNum = 10
                }));
                iStorage.AddCID("123456789", "2bfd19ad80d679853a690ceb72c7c041");
                var options = new GeTuiPushOptions()
                {
                    AppID = AppID,
                    AppKey = AppKey,
                    MasterSecret = MasterSecret
                };
                GeTuiPushV2Api api = new GeTuiPushV2Api();
                GeTuiPushService service = new GeTuiPushService(iStorage, options, api);
                try
                {
                    await service.PushMessageAsync(new PushMessageInDto()
                    {
                        title = "停机警告",
                        body = "已停机，请及时处理",
                        payload = JsonConvert.SerializeObject(new
                        {
                            msgId = new string[] { Guid.NewGuid().ToStr() },
                            text = $"停机时间：{DateTime.Now}"
                        }),
                        isall = false,
                        uid = new string[] { "123456789" }
                    });
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }
````

注意这里设置的CID，之前是写的一个guid，没有用真实的cid，注意替换掉，比如
````
iStorage.AddCID("123456789", "2bfd19ad80d679853a690ceb72c7c041");
````

**Comment by kiyeer** [comment]
嗯，这个cid我替换成自己的真实cid了。

**Comment by kiyeer** [comment]
测试了，大概是这个推送只能推在线消息，APP离线消息推送收不到。

**Comment by pinzi** [comment]
可能是接厂家通道了效果更好些

**Comment by pinzi** [comment]
> 测试了，大概是这个推送只能推在线消息，APP离线消息推送收不到。

离线消息是需要接厂家通道的，毕竟离线消息是系统级的推送，个推属于应用级别的推送，https://ask.dcloud.net.cn/article/36611

**Comment by kiyeer** [comment]
个推支持厂商通道推送的，uniapp后端web版就可以测试的。看文档，需要推送参数配置push_channel才行
"push_channel":{      
        "android":{      
            "ups":{      
                "notification":{      
                    "title":"安卓离线展示的标题",      
                    "body":"安卓离线展示的内容",      
                    "click_type":"intent",      
                    "intent":"intent:#Intent;launchFlags=0x04000000;action=android.intent.action.oppopush;component=io.dcloud.HBuilder/io.dcloud.PandoraEntry;S.UP-OL-SU=true;S.title=测试标题;S.content=测试内容;S.payload=test;end"      
                }      
            }      
        },      
      "ios":{      
            "type":"notify",      
            "payload":"自定义消息",      
            "aps":{      
                "alert":{      
                    "title":"苹果离线展示的标题",      
                    "body":"苹果离线展示的内容"      
                },      
                "content-available":0,    
                "sound":"default"     
            },      
            "auto_badge":"+1"      
        }      
}

**Comment by pinzi** [comment]
> 个推支持厂商通道推送的，uniapp后端web版就可以测试的。看文档，需要推送参数配置push_channel才行 "push_channel":{ "android":{ "ups":{ "notification":{ "title":"安卓离线展示的标题", "body":"安卓离线展示的内容", "click_type":"intent", "intent":"intent:#Intent;launchFlags=0x04000000;action=android.intent.action.oppopush;component=io.dcloud.HBuilder/io.dcloud.PandoraEntry;S.UP-OL-SU=true;S.title=测试标题;S.content=测试内容;S.payload=test;end" } } }, "ios":{ "type":"notify", "payload":"自定义消息", "aps":{ "alert":{ "title":"苹果离线展示的标题", "body":"苹果离线展示的内容" }, "content-available":0, "sound":"default" }, "auto_badge":"+1" } }

是的，需要申请相应的厂家开发者账号，uniapp后台可以配置。

**Comment by kiyeer** [comment]
嗯，是的。
