### ISSUE TITLE
如何配置厂家通道

### ISSUE THREAD

**Issue by Arvin-cmd** [pinzi/GeTui-PushApi-NetCoreSDK-V2#17]
如何配置厂家通道

**Comment by pinzi** [comment]
详见官方文档
https://docs.getui.com/getui/dos/third_party/
https://docs.getui.com/getui/mobile/vendor/vendor_open/
https://docs.getui.com/getui/server/rest_v2/third_party/

**Comment by Arvin-cmd** [comment]
没有个推账号   在uniapp后台开通的  可以吗

**Comment by pinzi** [comment]
看后台功能应该是可以的，但是我没用过
