### ISSUE TITLE
获取签权Token，设置缓存有效期似乎有问题

### ISSUE THREAD

**Issue by kiyeer** [pinzi/GeTui-PushApi-NetCoreSDK-V2#6]
public async Task<ApiResultOutDto<ApiAuthOutDto>> AuthAsync()
        {
            long _timestamp = GetTimeStamp();
            var result = await _api.AuthAsync(new ApiAuthInDto()
            {
                appkey = _options.AppKey,
                timestamp = _timestamp,
                sign = SHA256Helper.SHA256Encrypt(_options.AppKey + _timestamp + _options.MasterSecret),
                appId = _options.AppID
            });
            //缓存token
            if (result.code.Equals(0))
            {
                //token有效期，毫秒时间戳，将缓存有效期在token有效期基础上减少30秒，防止因网络传输导致获取到已过期的token，并提前刷新token
                long expire_time = result.data.expire_time - 30 * 1000;
                _iStorage.SaveToken(_options.AppID, result.data.token, TimeSpan.FromMilliseconds(expire_time));
            }
            return result;
        }

这里面expire_time应该要在减掉当前时间戳，不然过期时间远远超过了1天的有效期。

**Comment by pinzi** [comment]
大写的尴尬，这里的有效期是时间，我当成时长处理了。
